name: docker-compose-v1
version: 1.29.2
check: ${binary} version --short
flags:
- docker-compose-v1
tags:
- org/docker
- standard/docker
- container/compose
- type/cli
homepage: https://github.com/docker/compose
description: Define and run multi-container applications with Docker (v1)
renovate:
  datasource: github-releases
  package: docker/compose
  extractVersion: regex:^(?<major>1?)\.(?<minor>\d+?)\.(?<patch>\d+?)$