name: Report

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    paths:
    - scripts/report.sh
    - .github/workflows/report.yml

jobs:

  prepare:
    name: Report
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create report
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        make metadata.json
        bash scripts/report.sh >report.txt
        echo "report=$(cat report.txt)" >> ${GITHUB_ENV}

    - name: Store report
      uses: actions/upload-artifact@v3
      with:
        name: daily_report
        path: "report.txt"

    - name: send message
      uses: s3krit/matrix-message-action@v0.0.3
      with:
        room_id: ${{ secrets.MATRIX_ROOM_ID }}
        access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        message: "${{ env.report }}"
        server: "matrix.freiburg.social"